name: Secrets Variables and Environment Demo

on:
  workflow_dispatch:

env:
  WORKFLOW_ENV: "Written inside workflow file"

jobs:
  demo:
    name: Show Repo and Environment Values
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Show workflow env
        run: echo "WORKFLOW_ENV = $WORKFLOW_ENV"

      - name: Show repository variable
        run: echo "REPO_APP_NAME = ${{ vars.REPO_APP_NAME }}"

      - name: Show repository secret
        run: echo "REPO_SECRET = ${{ secrets.REPO_SECRET }}"

      - name: Show environment variable
        run: echo "ENV_NAME = ${{ vars.ENV_NAME }}"

      - name: Show environment secret
        run: echo "ENV_SECRET = ${{ secrets.ENV_SECRET }}"
